export const GetTokensViewport = 'GetTokensViewport.getTokensViewport'
export const HandleMessagePort = 'HandleMessagePort.handleMessagePort'
export const LoadTokenizer = 'Tokenizer.load'
export const SetLines = 'TextDocument.setLines'
export const TokenizeCodeBlock = 'Tokenizer.tokenizeCodeBlock'
export const TokenizeIncremental = 'TokenizeIncremental.tokenizeIncremental'
